version: '3'
services:
   app:
    container_name: node_app
    build: .
    ports:
      - 3000:3000
    restart: always
    links:
      - mongo
    network:
      - nodenw  
   mongo:
      image: mango:latest
      container_name: mongo_db
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MANGO_INTIDB_ROOT_PASSWORD: root
          MANGO_INITDB_DATABASE: node_db
      ports:
        - 27017:27017
      network:
        -nodenw  
volumes:
  nodevolume:
networks:
  nodenw: