version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:3000'
    networks:
      - test
    links:
      - mongo
     environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - MONGO_INITDB_ROOT_USERNAME=dbusername
      - MONGO_INITDB_ROOT_PASSWORD=dbpassword
      - HOST=localhost 
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dbusername
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dbpassword
    ports:
      - '27017:27017'
    networks:
      - test
networks:
   test:
     driver: 'bridge'
